# Generated by Django 3.1.1 on 2020-10-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blog/images/rpi.png', upload_to='blog/images/'),
        ),
    ]
