# Generated by Django 3.1.1 on 2020-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='static/blog/road2.jpeg', upload_to='portfolio/images/'),
        ),
    ]
